[sdl]
windowresolution=960x600
fullresolution=desktop
fullscreen=true
output=openglnb

[dosbox]
# 16 MB of RAM
memsize=16

[render]
# Preserve aspect ratio when scaling to fill the window
aspect=true
scaler=none

[cpu]
core=auto
cputype=486_slow
cycles=fixed 23800

[dos]
xms=true
ems=true
umb=true

[autoexec]
mount c .
c:
endless.exe
exit
